name: composite actions for react app
description: Install dependencies and build the app

inputs:
  node-version:
    required: true
    default: '20'
    type: string

runs:
  using: "composite"
  steps:
    
    - name: setup nodejs
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}

    - name: Install dependencies
      run: npm install
      shell: bash

    - name: Build app
      run: npm run build
      shell: bash  

    - name: Show output
      run: echo "App Built Successfully"
      shell: bash