name: Test Composite Actions

on:
  push:
    branches: [main]

jobs:
    build-using-composite:

        runs-on: self-hosted

        steps:
          - name: checkout repo
            uses: actions/checkout@v4

          - name: using composite actions
            uses: ./.github/actions/react-app-build
            with:
                node-version: '20'

          - name: deploy the app
            run: |
              sudo rm -rf /var/www/html/*
              sudo cp -r dist/* /var/www/html/
              sudo systemctl restart nginx

            
            