name: call the reusable workflow

on:
  push:
    branches: [main]
    paths:
      - '**/*.html'
      - '**/*.jsx'

jobs:
    call-workflow:
        uses: ./.github/workflows/react-reusable-workflow.yml
        with:
            node-version: '20'
            deploy: true